kivra/developer.kivra.com

documentation/index.yaml
documentation of usermatch endpoint
=> "usermatch" resource in documentation

documentation/index.yaml
Change to description text: payslip and partner API
=> Change to developer.kivra.com (descriptions)

documentation/index.yaml
How to add a link to the authentication chapter there?
=> Clarify scope expansion on tenant creation (#22)

documentation/index.yaml
@robin-svensson-kivra och @kbip 
I added documentation for Tenant API 2. Please have a look.
Note that I moved `v1` and `v2` into the endpoint path instead of in the `servers` path s it was before
=> Tenant API #2

documentation/index.yaml
More info here: https://github.com/kivra/kivra_nova/pull/104
=> fix: add max size for payment ref

swagger.yml
Preview: http://developer.kivra.com/jz-questions-to-sender-support/index.html
=> Point questions to Sender Support instead of dev@kivra.com

swagger.yml
information and example about the `invoice.reminder` type
=> add invoice.reminder type to documentation

swagger.yml
Corrected example for usermatch
=> Correct example for usermatch

swagger.yml
I added a link to the Receipt API with a short description
=> Link to Receipt API

swagger.yml
=> feat: added CompanyMatch on plus_active endpoint

swagger.yml
the path parameter "diffId" is missing a description
=> add parameter description for diffId

swagger.yml
Updated information according to request from Sofia (https://kivra.atlassian.net/browse/PMNT-66 and https://kivra.atlassian.net/browse/PMNT-74)
=> fix: update MPO documentation

swagger.yml
=> improved info om matching

swagger.yml
Just found some fields that the server sends and added them to the documentation
=> Added missing field that the Server sends

swagger.yml
This reverts commit f3d153b07a330912d41db5de72569a6d61b51a9b due a broken build.
=> Revert "Updated info on 500 errors"

swagger.yml
one error fixed and added 404 error if diffId is expired
=> fix and 404 for diffId

swagger.yml
See https://kivra.atlassian.net/browse/PTB-406 for requirements.
=> PTB:406 - Renamed sender_id -> tenant_key and id -> form_response_key

swagger.yml
Will have to verify this documentation with proper testing for each case in forms
=> feat: unified forms errors

swagger.yml
added info about how to use subject field
=> Paolokivra patch subject description

swagger.yml
=> [Draft] Add burger API

swagger.yml
We moved it after discussing with Wint: https://kivra.atlassian.net/browse/K4B-1687
=> [K4B-1687] move vat_amount into PartnerPaymentOption

swagger.yml
See [K4B-1835](https://kivra.atlassian.net/browse/K4B-1835).
[K4B-1835]: https://kivra.atlassian.net/browse/K4B-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [K4B-1835] Remove non-existent endpoint

receipt/schemas/json/prescription/v1.0/prescription-specification-definitions.json, receipt/schemas/json/prescription/v1.0/prescription-specification-schema.json, receipt/wiki/receipt-doc/prescription/example-prescription-specs.md, receipt/wiki/receipt-doc/prescription/example-prescription-specs/animal-prescription-1.json, receipt/wiki/receipt-doc/prescription/example-prescription-specs/human-prescription-1.json, receipt/wiki/receipt-doc/prescription/example-prescription-specs/human-prescription-2.json, receipt/wiki/receipt-doc/prescription/prescription-schema-description.md
=> fix: kvit-1778-2, updates to prescription specification docs after pharmacy review

swagger.yml
See [K4B-1943](https://kivra.atlassian.net/browse/K4B-1943).
[K4B-1943]: https://kivra.atlassian.net/browse/K4B-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [K4B-1943] Add delivery address to PAPIv3 response

swagger.yml
See [K4B-2064](https://kivra.atlassian.net/browse/K4B-2064).
Code changes [here](https://github.com/kivra/kivra_core/pull/4236).
[K4B-2064]: https://kivra.atlassian.net/browse/K4B-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [K4B-2064] Add sender icon url to content response

swagger.yml
Also clarify rule when several identifiers are provided
=> Add alternative identifiers (email and vat_numbers) to content v1 and v2

swagger.yml
Update docs to describe the new interpreter meta properties we added July 31.
See issues K4B-2015, K4B-2097.
=> Document the interpreter metadata on content in the Partner v3 API

swagger.yml
Updated docs to include new schema for verified account object in forms response
=> feat: update docs for verified account responses

swagger.yml
it should say "salary slip" not "payment slip"
=> Simple error fix

swagger.yml
The commit-by-commit history should tell the whole story.
Lemme know if something's off or I can choose better language.
=> fix: minor things

swagger.yml
Main PR: https://github.com/kivra/kivra_core/pull/3858
Changes can be seen live here: https://developer.kivra.com/ptf-699-shorter-termination-period/index.html
=> chore: [PTF-699] Changes sender grace period from 45 to 10 days

swagger.yml
Add documentation for new question type multipe_options in forms.
=> feat: [STS-2611] document forms multi_options

swagger.yml
See [K4B-2640](https://kivra.atlassian.net/browse/K4B-2640).
[K4B-2640]: https://kivra.atlassian.net/browse/K4B-2640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [K4B-2640] Add match by VAT number

swagger.yml
=> Update swagger.yml fixed typo

swagger.yml
Added description for new content type `invite.sign`
=> feat: add doc for invite.sign

swagger.yml
Added info on protocol expected for invites and bookings. Added info for letter.signed
=> feat: add docs for protocol and letter.signed

swagger.yml
See [K4B-3007](https://kivra.atlassian.net/browse/K4B-3007).
See https://github.com/kivra/kivra_core/pull/5027.
[K4B-3007]: https://kivra.atlassian.net/browse/K4B-3007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [K4B-3007] Remove vatnr check

swagger.yml
update retain doc after user feedback
=> Update retain description

swagger.yml
Add the description field for `invites.sign`
=> chore: [STS-3203] add description field to invites_sign

receipt/clientapi/changelog/changelog.md, receipt/clientapi/clientapi.json, receipt/posapi/changelog/changelog.md, receipt/posapi/posapi.yaml
* update of errors
* various small fixes
=> fix: updates to receipts documentation

swagger.yml
fix link as it pointed to an outdated page
=> fix outdated link

swagger.yml
BETA version of registered letters.
=> fix: registered letters BETA

swagger.yml
Add two content types:
- invoice.donation
- invoice.paymentnotice
Jira ticket for reference: https://kivra.atlassian.net/browse/PMNT-2934
=> PMNT-2934 Add two new content types

swagger.yml
My editor stripped some trailing whitespace. It's in a separate commit and I can break it out into a separate commit if it's too distracting.
Preview: https://developer.kivra.com/k4b-3311-document-papi-webhooks/index.html#tag/Partner-API-v3
=> K4B-3311 document PAPI webhooks

swagger.yml
=> fix swagger.yml

swagger.yml
See [K4B-3419](https://kivra.atlassian.net/browse/K4B-3419).
See https://github.com/kivra/k4b_notification/pull/228.
[K4B-3419]: https://kivra.atlassian.net/browse/K4B-3419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: document webhooks for partner de-/activation

swagger.yml
Review of the introductory text - part 1
=> Review of introductory text - part 1

swagger.yml
https://github.com/kivra/developer.kivra.com/pull/231 deleted some stuff it shouldn't have.
=> fix: re-add deleted stuff

swagger.yml
=> Review of documentation

receipt/posapi/posapi.yaml, receipt/wiki/receipt-doc/retail/retail-schema-description.md
Added info about where to troubleshoot when creating reciept.
=> fix: Receipt troubleshooting
